---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://ttop.github.io/trmnl-demo/data.json
polling_headers: ''
polling_body: 
id: 192286
name: My Plugin
refresh_interval: 1440
